### ISSUE TITLE
1.13 tab completions

### ISSUE THREAD

**Issue by untuned** [TotalFreedomMC/TotalFreedomMod#130]
add command tab completions for 1.13, for example /saconfig has list, clean, reload, etc.

**Comment by script-head** [comment]
I've tried this on a command however nothing I do works. I think I have to modify Aero in order for this to work.

**Comment by ncurran02** [comment]
@ZeroEpoch1969 I have modified Aero to support 1.13.2 and also added tab complete.
https://github.com/Focusvity/Aero
Tab Complete: https://github.com/Focusvity/Aero/blob/1.13.2/src/main/java/net/pravian/aero/command/executor/AbstractCommandExecutor.java#L59

I can confirm that it's working using the latest changes of TFM and my version of Aero.

**Comment by script-head** [comment]
added af
