### ISSUE TITLE
NoClassDefFoundException popping up in log

### ISSUE THREAD

**Issue by ncurran02** [TotalFreedomMC/TotalFreedomMod#137]
![image](https://user-images.githubusercontent.com/30569566/56575084-3961e800-6608-11e9-9522-6a95291ec9dd.png)
AFAIK this applies to list, schematics and players. I'm assuming someone didn't compile it properly?

It's doing the same for EntityWiper
![image](https://user-images.githubusercontent.com/30569566/56575599-7aa6c780-6609-11e9-9bf3-707fd7b80e47.png)

**Comment by lemonsked** [comment]
@ZeroEpoch1969

**Comment by script-head** [comment]
wasn't compiled right.
