### ISSUE TITLE
use UUIDs for developers

### ISSUE THREAD

**Issue by untuned** [TotalFreedomMC/TotalFreedomMod#146]
to avoid this: https://github.com/TFPatches/TotalFreedomMod/commit/eccf940b811be9d717988d648273b09b2944a656

**Comment by ncurran02** [comment]
While UUIDs does work for cracked, it’s safe to keep it only for usernames in case if anyone was cracked.

**Comment by untuned** [comment]
> While UUIDs does work for cracked, it’s safe to keep it only for usernames in case if anyone was cracked.

yeah i forgot about that part thanks
