### ISSUE TITLE
beehives

### ISSUE THREAD

**Issue by robingall2910** [TotalFreedomMC/TotalFreedomMod#171]
bees can't come out of the hives at night (if the server is set to let day go by), entitywiper removes them, so it's infinitely trying to shit out bees

needs to be where bees are an exception to the entitywiper of some sort, but i don't really know how to figure that one out

**Comment by ncurran02** [comment]
Add `-bee` in entity wiper command to remove bees?

**Comment by robingall2910** [comment]
that isn't the issue, the issue is that if you have the entitywipe thing toggled to on, bees keep getting immediately removed, and minecraft/paper keep trying to respawn them, but them won't let them, and it's just this infinite recursive thing going on until you either reload tfm or break the block

**Comment by Deauthorized** [comment]
what if you cancel the spawn event if the reason for the spawn is "BEEHIVE"

**Comment by ncurran02** [comment]
Then we’ll just remove the bee functionality which isn’t a good idea as many people want bees.

**Comment by robingall2910** [comment]
plus that's not what we're going for, not trying to literally block everything

**Comment by ncurran02** [comment]
Why not add a check if they are bees and don't wipe them in automated entity wiper but allow bees to be wiped in `/ew` command.

**Comment by violetwtf** [comment]
Made a PR to adress this: #183 @robingall2910

**Comment by viomck** [comment]
I've thought of a way to address this, give me a few to implement it

**Comment by viomck** [comment]
#184 stops the removal of bees if it's a scheduled wipe, so that admins can still manually wipe them with `/ew`.

**Comment by violetwtf** [comment]
this is fixed someone close this ffs

**Comment by Ivanomoly** [comment]
impatient people 😳
