### ISSUE TITLE
Change Gunpoweder in Item fun to other item

### ISSUE THREAD

**Issue by DragonSlayer2189** [TotalFreedomMC/TotalFreedomMod#203]
in the Item_Fun.java file the following is within

` 
case GUNPOWDER:
            {
                if (!fPlayer.isMP44Armed())
                {
                    break;
                }

                event.setCancelled(true);

                if (fPlayer.toggleMP44Firing())
                {
                    fPlayer.startArrowShooter(plugin);
                }
                else
                {
                    fPlayer.stopArrowShooter();
                }
                break;
            }`
the GUNPOWDER thing should be changed to something like SUGAR to prevent conflicts with voxelsnipper

(also this is my first time ever making an issue thingy so woo)

**Comment by fionnn** [comment]
A https://github.com/TFPatches/TotalFreedomMod/pull/204

**Comment by ajaxvp** [comment]
pull request was closed by seth, so this issue will be closed as well
