### ISSUE TITLE
range bans in regular bans are a huge no-no

### ISSUE THREAD

**Issue by VideoGameSmash12** [TotalFreedomMC/TotalFreedomMod#209]
Range banning should only apply to things where it is logical to use them (like permbans). However, for some reason, banning people also rangebans their IP address. This functionality should be removed from regular bans to avoid cases of innocent players getting banned.

**Comment by script-head** [comment]
I'm not removing rangebans from 24 hour bans as they only last a day and are a great way to stop dynamic ip bypassing.
