### ISSUE TITLE
Unblock /reactionbar

### ISSUE THREAD

**Issue by Nathaniel-428** [TotalFreedomMC/TotalFreedomMod#213]
About a month ago, you blocked /reactionbar because a piston tried to move a chest (or that's how I remembered it). I bet the server will work fine now with /reactionbar enabled.

**Comment by VideoGameSmash12** [comment]
you shouldn't even be on in the first place

**Comment by ncurran02** [comment]
`/reactionbar` doesn't do anything remotely similar to the piston.

**Comment by Nathaniel-428** [comment]
> 
> 
> `/reactionbar` doesn't do anything remotely similar to the piston.

That's what seth believed at that time. Even though he's likely incorrect.

**Comment by ncurran02** [comment]
> > `/reactionbar` doesn't do anything remotely similar to the piston.
> 
> That's what seth believed at that time. Even though he's likely incorrect.

Seth said he blocked it because it could crash other people. I don't see how you got that from.

**Comment by Nathaniel-428** [comment]
>>
> Seth said he blocked it because it could crash other people. I don't see how you got that from.

Well, that's how I remembered it. I could be wrong

**Comment by script-head** [comment]
I'm replacing it with a boss bar.
