### ISSUE TITLE
Replace Telnet with SSH

### ISSUE THREAD

**Issue by ghost** [TotalFreedomMC/TotalFreedomMod#24]
http://totalfreedom.boards.net/thread/57950/replace-telnet-ssh-bukkittelnet

For security reasoning among the protocol being old, TotalFreedom should move to SSH as a replacement for BukkitTelnet.

https://mina.apache.org/sshd-project/embedding_ssh.html
https://mina.apache.org/sshd-project/apidocs/

**Comment by ncurran02** [comment]
Just throwing this in if you guys want to use it: https://github.com/Focusvity/BukkitSSH

**Comment by lemonsked** [comment]
in progress
