### ISSUE TITLE
Verification System is Broken (for me at least)

### ISSUE THREAD

**Issue by XenVoltz** [TotalFreedomMC/TotalFreedomMod#244]
This has happened twice. When I am flagged as an imposter, I verify via Discord, and it doesn't work. It just says I verified, but then gives me an "[Imp]" tag. I can't do anything else. The last time this happened we had to restart the server for it to be fixed. Manually adding/removing me didn't work.

**Comment by mgejay** [comment]
This is happening on total freedom as we speak? @ZeroEpoch1969

**Comment by XenVoltz** [comment]
> This is happening on total freedom as we speak? @ZeroEpoch1969 

Yes, I currently am still not supered because of this issue. I also have access to no OP commands.

**Comment by Telesphoreo** [comment]
Fixed in #266
