### ISSUE TITLE
Administrators logged-in under the same IP-address

### ISSUE THREAD

**Issue by ghost** [TotalFreedomMC/TotalFreedomMod#26]
When an administrator logs-in to the server and another account with the same IP-address, issues like an administrator can't see adminchat but can send messages to the adminchat. The same issues occur with issuing punishments.

**Comment by lemonsked** [comment]
We should make both IP and username required to be the same for user to be supered

**Comment by ncurran02** [comment]
Like @OxLemonxO says, the way for this to work if we check the username first before checking the ip address.
