### ISSUE TITLE
/tban updates

### ISSUE THREAD

**Issue by ghost** [TotalFreedomMC/TotalFreedomMod#28]
1. `/tban` should be an alias of `/tempban` anyway
2. If `/tban` isn't added as an alias, a reason field should be added

**Comment by lemonsked** [comment]
Suggestion thread on TF Forums needed.

**Comment by ncurran02** [comment]
`/tban` and `/tempban` are different. `tban` is for 5 minutes (alias to `noob`) and `tempban` is to ban people with a time specified.

**Comment by ghost** [comment]
@Focusvity I'm saying that they should be the same command. It's completely unnecessary to make a new command because administrators cannot add `5m` before execution.

**Comment by ncurran02** [comment]
You do make a good point.

**Comment by robingall2910** [comment]
only if you keep the alias of /tban which is /noob, i'm fine with this
