### ISSUE TITLE
Add Clan as a rank

### ISSUE THREAD

**Issue by ghost** [TotalFreedomMC/TotalFreedomMod#32]
Clan should be added as a rank (not a title as `/saconfig setrank <rank>` cannot add it to users) to prevent confusion with operators.

**Comment by ghost** [comment]
#31

**Comment by lemonsked** [comment]
Suggestion thread on TF Forums needed.

**Comment by robingall2910** [comment]
i'd rather not let this happen, especially if you were to add it, it wouldn't make sense to call it a clanforge admin, since we're not using that panel

**Comment by lemonsked** [comment]
I agree with Robin, if the admins want it this can be rethought.
