### ISSUE TITLE
MB Server Changes

### ISSUE THREAD

**Issue by peclarke** [TotalFreedomMC/TotalFreedomMod#36]
As seen in this thread: http://totalfreedom.boards.net/thread/58494/masterbuilder-server-changes

1. Masterbuilders gain a toggleable title. 
            - Both MB and Admin tag will have to be displayed for Admins according to the conduct pol.

2. Second Masterbuilder world
           - Masterbuilders gain their own world to build in. They would have to verify like admins to access it. Other players/admins can view the MB world however, they would not be allowed to edit anything. Maybe place them in spectator mode if there isn't an easier way to block all edits. The only people allowed to edit the MB world would be Masterbuilders and Executives. Dusty and xfilez would handle all reports coming from the world.

**Comment by robingall2910** [comment]
how about we keep it as it only displays the admin rank, and if they're not an admin, show the master-builder tag on the list and on the chat?
