### ISSUE TITLE
Clearing nicknames removes italics

### ISSUE THREAD

**Issue by ghost** [TotalFreedomMC/TotalFreedomMod#41]
Italics are allowed according to the conduct policy, however, `/nickclear` removes this formatting code.

**Comment by robingall2910** [comment]
this should be reported on the main repository as well

**Comment by lemonsked** [comment]
# Blocked Chat Codes - Use &code,&code2,&code3 (No spaces)
blocked_chatcodes: '&0,&k,&m,&n'


config needs editing.

**Comment by ncurran02** [comment]
If Windows added `&o` to config, it would be why it would clear. I implemented this system so we can rely on config instead of recompiling TFM after every changes.
