### ISSUE TITLE
Banning impostor's IP-address

### ISSUE THREAD

**Issue by ghost** [TotalFreedomMC/TotalFreedomMod#42]
Original issue from https://github.com/TotalFreedom/TotalFreedomMod/issues/2137
--
"I think we should implement something like when an impostor joins, we can still use /gtfo <player> [reason] but it would check if the name is an admin, and if it is, the impostor’s IP would be banned instead of both. This is to avoid admins being banned if their IP isn’t supered. Thoughts? (Sorry if there’s any typo or anything, I am on my mobile at the moment.)"

**Comment by robingall2910** [comment]
`the impostor’s IP would be banned instead of both.` and what if you ban the admin, even though they just weren't supered? sure there can be a comparison of the ips on which ones supered or not, but still
