### ISSUE TITLE
Fix ban reason issue

### ISSUE THREAD

**Issue by ghost** [TotalFreedomMC/TotalFreedomMod#43]
Original issue from https://github.com/TotalFreedom/TotalFreedomMod/issues/2112
--
"Currently if you /tempban or /gtfo a player, the reason you used in that command it what is displayed whenever the player is banned, regardless of it you re-ban them later on. Given /glist ban has the ability to now accept reasons, it would be preferable if it would overwrite the original ban reason with the updated one, it saves needing to /glist unban and then /glist ban [Slightly different new reason]"

**Comment by robingall2910** [comment]
this can happen, just update the current ban on bans.yml, all we need is just a command to support that

**Comment by script-head** [comment]
I'm probably going to rewrite /gtfo to do online and offline bans in the future.
