### ISSUE TITLE
Command spy should remain on toggle

### ISSUE THREAD

**Issue by ghost** [TotalFreedomMC/TotalFreedomMod#45]
If an administrator were to join and activate [or deactivate] `/commandspy` and leave, `/commandspy` should remain enabled [or disabled] on join until it is toggled again.

**Comment by untuned** [comment]
This should be the same for other things as well, such as `/potionspy` or `/jumppads enable/disable`

**Comment by Telesphoreo** [comment]
Fixed for commandspy: https://github.com/TFPatches/TotalFreedomMod/commit/ffbe71f5ddd579e73596a54f9bffedf74419f4a1
