### ISSUE TITLE
/wipecoreprotectdata <world>

### ISSUE THREAD

**Issue by untuned** [TotalFreedomMC/TotalFreedomMod#81]
http://totalfreedom.boards.net/thread/60703/coreprotect-database

worlds are stored in IDs, which can be found in the "world" table
aka delete all entries with world id of the "world" argument

tables that should be modified (i think):
> block
> chat
> command
> container
> session
> sign
> skull

**Comment by script-head** [comment]
There really isn't a need to wipe data for worlds other than the flatlands.
