### ISSUE TITLE
Delete the OxLemonxO-patch-1 branch

### ISSUE THREAD

**Issue by Telesphoreo** [TotalFreedomMC/TotalFreedomMod#84]
I suggest we delete this branch and never add it back. I also suggest we make adding "package delivery" (in any arrangement) forbidden from being added to the Developer Array List.

**Comment by script-head** [comment]
disagree

**Comment by script-head** [comment]
human right violations

**Comment by Telesphoreo** [comment]
no goddamnit

**Comment by Telesphoreo** [comment]
you better fix it
